### ISSUE TITLE
DirectInput hook never gets called

### ISSUE THREAD

**Issue by Eric5766** [DestroyerDarkNess/RenderSpy#2]
Using the imgui example - That itself works great however I noticed inputs are still getting through to the main window.  I have a very similar dx9 hook+imgui in C++ which works great by simply checking if the imgui menu is open in WndProc, if it is, it passes the input to the imgui handler then blocks the original WndProc call.  Using this example however (With SetWindowLongPtr.BlockInput), preventing the call of the original WndProc causes all input to not work even if passed to the imgui handler first.

I wasn't sure why the DirectInput hook wasn't working in this case as this should help bypass the above, but take the following code:

```
DirectInputHook DirectInputHook_Hook = new DirectInputHook();
DirectInputHook_Hook.WindowHandle = GameHandle;
DirectInputHook_Hook.Install();
CurrentHooks.Add(DirectInputHook_Hook);
DirectInputHook_Hook.GetDeviceState += (IntPtr hDevice, int cbData, IntPtr lpvData) => {
  Console.WriteLine("GetDeviceState called");
  return 0;
}
```

Never seems to run?

**Comment by DestroyerDarkNess** [comment]
What game are you injecting?

The DirectInput Hook is intended for games that use dinput8.dll to process input.

There are also other hooks for input, for example rawinput.

**Comment by Eric5766** [comment]
I'm injecting into a copy of WoW (On my own private server) - The game does use dinput8, dx9 + 32 bit (Wotlk client).  I hijack dinput8.dll for my C++ project on the same client to load without an injector.

RenderSpy confirms dinput is detected, and the above code to install the hook works, but GetDeviceState still doesn't seem to be called.
![Screenshot](https://github.com/DestroyerDarkNess/RenderSpy/assets/9409967/3d54da1e-f0ab-4d21-bdb9-248bb0652a12)

I get this using the imgui internal example with minimal modifications (Only changes have been to remove NetBuilder as I use my own injector for managed dlls)

**Comment by DestroyerDarkNess** [comment]
Okay, let's solve this, talk to me on my discord: Destroyer#8328

**Comment by Eric5766** [comment]
Has been sorted - My error.  Can work around by capturing the imgui input outside of hooks.

Many thanks for taking the time to have a look with me!
